import resumeExportService from "./resumeExportService";

export interface ATSAnalysisResult {
  overallScore: number;
  scores: Record<string, number>;
  criticalIssues: string[];
  warnings: string[];
  passed: string[];
  foundKeywords: string[];
  missingKeywords: string[];
  suggestedKeywords: string[];
  fileName: string;
  fileSize: string;
  uploadDate: string;
}

export function generateATSReportHTML(result: ATSAnalysisResult, recommendations: string[] = []): string {
  const scoreColor =
    result.overallScore >= 80 ? "#16a34a" : result.overallScore >= 60 ? "#ca8a04" : "#dc2626";

  const section = (title: string, body: string) => `
    <div style="margin: 16px 0; padding: 12px; border: 1px solid #e5e7eb; border-radius: 12px;">
      <h3 style="margin: 0 0 8px 0; color: #111827; font-size: 16px;">${title}</h3>
      ${body}
    </div>
  `;

  const chipList = (items: string[], color = "#2563eb") =>
    `<div style="display:flex; flex-wrap:wrap; gap:8px;">${items
      .map(
        (k) =>
          `<span style="padding:6px 10px;border-radius:9999px;background:${color}1A;color:${color};border:1px solid ${color}33;font-size:12px;">${k}</span>`
      )
      .join("")}</div>`;

  const scoreRows = Object.entries(result.scores)
    .map(
      ([k, v]) => `
      <div style="display:flex;align-items:center;justify-content:space-between;margin:6px 0;">
        <span style="color:#374151;text-transform:capitalize">${k}</span>
        <span style="color:${v >= 80 ? "#16a34a" : v >= 60 ? "#ca8a04" : "#dc2626"};font-weight:600">${v}</span>
      </div>
      <div style="height:8px;background:#e5e7eb;border-radius:6px;overflow:hidden;">
        <div style="height:100%;width:${v}%;background:linear-gradient(90deg,#3b82f6,#8b5cf6)"></div>
      </div>
    `
    )
    .join("");

  return `
  <!doctype html>
  <html>
    <head>
      <meta charset="utf-8"/>
      <title>ATS Report - ${result.fileName}</title>
      <style>
        @page { size: A4; margin: 18mm; }
        body { font-family: Arial, Helvetica, sans-serif; color: #111827; }
      </style>
    </head>
    <body>
      <h1 style="margin:0 0 12px 0;font-size:22px;">ATS Compatibility Report</h1>
      <div style="color:#6b7280;font-size:12px;margin-bottom:16px;">Generated by Estel – AI Career Companion</div>

      <div style="display:flex;gap:16px;margin-bottom:16px;">
        <div style="flex:1;padding:16px;border:1px solid #e5e7eb;border-radius:12px;">
          <div style="font-size:12px;color:#6b7280;margin-bottom:4px;">Overall Score</div>
          <div style="font-size:36px;font-weight:700;color:${scoreColor}">${result.overallScore}</div>
          <div style="height:10px;background:#e5e7eb;border-radius:6px;overflow:hidden;margin-top:8px;">
            <div style="height:100%;width:${result.overallScore}%;background:linear-gradient(90deg,#10b981,#06b6d4)"></div>
          </div>
        </div>
        <div style="flex:1;padding:16px;border:1px solid #e5e7eb;border-radius:12px;">
          <div style="font-size:12px;color:#6b7280;margin-bottom:8px;">File Details</div>
          <div style="font-size:14px;">${result.fileName}</div>
          <div style="font-size:12px;color:#6b7280;margin-top:4px;">${result.fileSize} • ${result.uploadDate}</div>
        </div>
      </div>

      ${section("Score Breakdown", `<div>${scoreRows}</div>`)}

      ${
        result.criticalIssues.length
          ? section(
              `Critical Issues (${result.criticalIssues.length})`,
              "<ul style='margin:0;padding-left:18px;color:#b91c1c'>" +
                result.criticalIssues.map((i) => `<li style="margin:4px 0;">${i}</li>`).join("") +
                "</ul>"
            )
          : ""
      }
      ${
        result.warnings.length
          ? section(
              `Warnings (${result.warnings.length})`,
              "<ul style='margin:0;padding-left:18px;color:#92400e'>" +
                result.warnings.map((i) => `<li style="margin:4px 0;">${i}</li>`).join("") +
                "</ul>"
            )
          : ""
      }
      ${
        result.passed.length
          ? section(
              `Passed Checks (${result.passed.length})`,
              "<ul style='margin:0;padding-left:18px;color:#065f46'>" +
                result.passed.map((i) => `<li style="margin:4px 0;">${i}</li>`).join("") +
                "</ul>"
            )
          : ""
      }

      ${result.foundKeywords.length ? section("Found Keywords", chipList(result.foundKeywords, "#059669")) : ""}
      ${result.missingKeywords.length ? section("Missing Keywords", chipList(result.missingKeywords, "#dc2626")) : ""}
      ${
        result.suggestedKeywords.length
          ? section("Suggested Keywords", chipList(result.suggestedKeywords, "#2563eb"))
          : ""
      }

      ${
        recommendations.length
          ? section(
              "AI Recommendations",
              "<ol style='margin:0;padding-left:18px;color:#111827'>" +
                recommendations.map((r) => `<li style="margin:6px 0;">${r}</li>`).join("") +
                "</ol>"
            )
          : ""
      }

      <div style="margin-top:16px;color:#6b7280;font-size:11px;">© ${new Date().getFullYear()} CVSaathi</div>
    </body>
  </html>`;
}

export async function exportATSReportWeb(result: ATSAnalysisResult, recommendations: string[] = []) {
  const html = generateATSReportHTML(result, recommendations);
  const safe = result.fileName?.replace(/\s+/g, "_").toLowerCase() || "ats_report";
  const fileName = `${safe}_${Date.now()}.pdf`;

  const url = await resumeExportService.exportPdf(html, fileName);
  if (url) {
    window.open(url, "_blank", "noopener,noreferrer");
    return true;
  }
  return false;
}


