import resumeExportService from "./resumeExportService";

export interface SkillGapResults {
  overallScore?: number;
  matchPercentage?: number;
  skillDistribution?: { technical: number; softSkills: number; domain: number };
  skillGaps: Array<{ name: string; current: number; required: number; gap: number; priority: string; category: string }>;
  recommendations?: string[];
  roadmap?: string[];
  timeline?: Record<string, string[]>;
  salaryRange?: { currency: string; min: number; max: number };
}

export interface SkillGapProfile {
  userType: string;
  education: string;
  targetRole: string;
  industry: string;
  location: string;
  currentSkills: { name: string; level: number }[];
}

export function generateSkillGapReportHTML(profile: SkillGapProfile, data: SkillGapResults): string {
  const score = data.overallScore ?? data.matchPercentage ?? 0;
  const scoreColor = score >= 80 ? "#16a34a" : score >= 60 ? "#ca8a04" : "#dc2626";

  const section = (title: string, body: string) => `
    <div style="margin: 16px 0; padding: 12px; border: 1px solid #e5e7eb; border-radius: 12px;">
      <h3 style="margin: 0 0 8px 0; color: #111827; font-size: 16px;">${title}</h3>
      ${body}
    </div>
  `;

  const gapRows = (data.skillGaps || [])
    .map(
      (g) => `
      <div style="display:flex;justify-content:space-between;align-items:center;margin:8px 0;padding:8px;border-radius:8px;background:#f9fafb">
        <div>
          <div style="font-weight:600;color:#111827">${g.name}</div>
          <div style="font-size:12px;color:#6b7280">${g.category} • Priority: ${g.priority}</div>
        </div>
        <div style="min-width:180px;text-align:right;font-size:12px;color:#374151">
          <div>Current: ${g.current} • Required: ${g.required}</div>
          <div>Gap: <b>${g.gap}</b></div>
        </div>
      </div>
    `
    )
    .join("");

  const timeline = data.timeline || {};
  const timelineBlocks = Object.entries(timeline)
    .map(
      ([period, tasks]) => `
        <div style="margin:10px 0;">
          <div style="font-size:12px;color:#0891b2;margin-bottom:6px;">
            ${period === "30days" ? "📅 First 30 Days" : period === "60days" ? "📅 Next 30 Days (60 total)" : "📅 Final 30 Days (90 total)"}
          </div>
          <ul style="margin:0;padding-left:18px;color:#111827">
            ${(tasks || []).map((t) => `<li style="margin:4px 0;">${t}</li>`).join("")}
          </ul>
        </div>
      `
    )
    .join("");

  const dist = data.skillDistribution || { technical: 0, softSkills: 0, domain: 0 };

  return `
  <!doctype html>
  <html>
    <head>
      <meta charset="utf-8"/>
      <title>Skill Gap Report - ${profile.targetRole || "Role"}</title>
      <style>
        @page { size: A4; margin: 18mm; }
        body { font-family: Arial, Helvetica, sans-serif; color: #111827; }
      </style>
    </head>
    <body>
      <h1 style="margin:0 0 12px 0;font-size:22px;">Skill Gap Analysis</h1>
      <div style="color:#6b7280;font-size:12px;margin-bottom:16px;">Generated by Estel – AI Career Companion</div>

      <div style="display:flex;gap:16px;margin-bottom:16px;">
        <div style="flex:1;padding:16px;border:1px solid #e5e7eb;border-radius:12px;">
          <div style="font-size:12px;color:#6b7280;margin-bottom:4px;">Overall Match</div>
          <div style="font-size:36px;font-weight:700;color:${scoreColor}">${score}%</div>
          <div style="height:10px;background:#e5e7eb;border-radius:6px;overflow:hidden;margin-top:8px;">
            <div style="height:100%;width:${score}%;background:linear-gradient(90deg,#14b8a6,#06b6d4)"></div>
          </div>
        </div>
        <div style="flex:1;padding:16px;border:1px solid #e5e7eb;border-radius:12px;">
          <div style="font-size:12px;color:#6b7280;margin-bottom:8px;">Target</div>
          <div style="font-size:14px;font-weight:600">${profile.targetRole || "—"}</div>
          <div style="font-size:12px;color:#6b7280;margin-top:4px;">${profile.industry || "General"} • ${profile.location || "—"}</div>
        </div>
      </div>

      ${section("Skill Distribution", `
        <div style="font-size:12px;color:#374151;margin-bottom:6px;">Technical: <b>${dist.technical}%</b></div>
        <div style="height:8px;background:#e5e7eb;border-radius:6px;overflow:hidden;margin-bottom:8px;">
          <div style="height:100%;width:${dist.technical}%;background:linear-gradient(90deg,#3b82f6,#06b6d4)"></div>
        </div>
        <div style="font-size:12px;color:#374151;margin-bottom:6px;">Soft Skills: <b>${dist.softSkills}%</b></div>
        <div style="height:8px;background:#e5e7eb;border-radius:6px;overflow:hidden;margin-bottom:8px;">
          <div style="height:100%;width:${dist.softSkills}%;background:linear-gradient(90deg,#a855f7,#ec4899)"></div>
        </div>
        <div style="font-size:12px;color:#374151;margin-bottom:6px;">Domain Knowledge: <b>${dist.domain}%</b></div>
        <div style="height:8px;background:#e5e7eb;border-radius:6px;overflow:hidden;">
          <div style="height:100%;width:${dist.domain}%;background:linear-gradient(90deg,#60a5fa,#1d4ed8)"></div>
        </div>
      `)}

      ${section("Skill Gaps", gapRows || "<div style='color:#6b7280'>No gaps identified.</div>")}

      ${
        data.recommendations && data.recommendations.length
          ? section(
              "Recommendations",
              "<ol style='margin:0;padding-left:18px;color:#111827'>" +
                data.recommendations.map((r) => `<li style="margin:6px 0;">${r}</li>`).join("") +
                "</ol>"
            )
          : ""
      }

      ${timelineBlocks ? section("30/60/90 Day Learning Roadmap", timelineBlocks) : ""}

      ${
        data.salaryRange
          ? section(
              "Salary Insights",
              `<div style="font-size:14px;">${data.salaryRange.currency}${Math.round(
                (data.salaryRange.min || 0) / 1000
              )}K - ${Math.round((data.salaryRange.max || 0) / 1000)}K</div><div style="font-size:12px;color:#6b7280">Per annum</div>`
            )
          : ""
      }

      <div style="margin-top:16px;color:#6b7280;font-size:11px;">© ${new Date().getFullYear()} CVSaathi</div>
    </body>
  </html>`;
}

export async function exportSkillGapReportWeb(profile: SkillGapProfile, results: SkillGapResults) {
  const html = generateSkillGapReportHTML(profile, results);
  const safe = (profile.targetRole || "skill_gap").replace(/\s+/g, "_").toLowerCase();
  const fileName = `${safe}_${Date.now()}.pdf`;

  const url = await resumeExportService.exportPdf(html, fileName);
  if (url) {
    window.open(url, "_blank", "noopener,noreferrer");
    return true;
  }
  return false;
}


